kind: pipeline
name: syntax-php7.3

steps:
  - name: syntax-php7.3
    image: nextcloudci/php7.3:php7.3-5
    environment:
      APP_NAME: workflow_script
      CORE_BRANCH: stable20
      DB: sqlite
    commands:
      # Pre-setup steps
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server/apps/$APP_NAME
      - composer install
      - ./vendor/bin/parallel-lint --exclude ./vendor/ .

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

type: docker
